spring.application.name=PuntoSimplex

# 1. URL de Conexión (El sistema intenta conectarse a este nombre)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

# 2. Credenciales del Servidor PostgreSQL (¡Usa tus credenciales!)
spring.datasource.username=postgres
spring.datasource.password=Jamv3123

spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
# 3. JPA/Hibernate (Permite que el código cree las tablas)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Archivo: src/main/resources/application.properties

# Configuraciones de la Aplicación


# Configuraciones de SpringDoc/OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=com.restaurente.puntoSimplex
springdoc.version=1.0.0
