spring.application.name=PuntoSimplex

# 1. URL de Conexión (El sistema intenta conectarse a este nombre)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#2 Logs
# 2. Credenciales del Servidor PostgreSQL (¡Usa tus credenciales!)
spring.datasource.username=postgres
spring.datasource.password=Jamv3123

# 2. JPA/Hibernate
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# 3. JPA/Hibernate (Permite que el código cree las tablas)
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Archivo: application.properties
spring.jpa.properties.hibernate.globally_quoted_identifiers=true


# Archivo: src/main/resources/application.properties

# Configuraciones de la Aplicación


#3 Configuraciones de SpringDoc/OpenAPI restaurente
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=com.restaurante.puntoSimplex
springdoc.version=1.0.0

# 4. Configuraciones de JWT
# Tiempo de Expiración del Token (en milisegundos).
# 86400000 ms = 24 horas. (1000ms * 60s * 60m * 24h)
jwt.secret=LdJoFOCOtc/5fshNBN6Kj1CWM+PBZ8nJLNWe3F/RXSg=
jwt.expiration=86400000
